### PR TITLE
Fixes #6 - Firewall Testing page has broken/outdated links

### LINKED ISSUE #6: Firewall Testing page has broken/outdated links
The Firewall Testing page (https://firehol.org/guides/firewall-testing/) has broken/outdated links, as well as many links that can be upgraded to HTTPS.

I'll make the needed changes, and submit a pull request.

### PR DESCRIPTION
**Pull request by Gitoffthelawn**
Also upgraded links to HTTPS.

Feel free to edit my changes before accepting pull request if you know replacement URLs for either of the URLs removed.

### CODE REVIEW

**Review by philwhineray — APPROVED** [review]
Thanks!

**Comment by philwhineray** [comment]
Looks like the scripts have bit-rotted since the last push :-( I'll take a look when I get a chance

**Comment by philwhineray** [comment]
I've updated the site manually for now; thanks again

**Comment by Gitoffthelawn** [comment]
You're welcome.  Thank you for the useful tools!

**Pull request merged**
